project:
  type: website
  output-dir: docs

website:
  title: "William Okech"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Training
        href: training.qmd
      - text: Research
        menu:
          - text: Research Interests
            href: research/research_interests.qmd
          - text: STEM Readings
            href: research/reading_stem.qmd  
          - text: Science Communication
            href: research/sci_comm.qmd
          - text: Journal Club
            href: research/journal_club.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

extensions:
  - jmgirard/embedpdf