project:
  type: website
  output-dir: docs

website:
  title: "William Okech"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Training
        href: training.qmd
      - text: Research
        menu:
          - text: Research Interests
            href: research/research_interests.qmd
          - text: Readings for the Young Scientist
            href: research/reading_stem.qmd  
          - text: Science Communication
            href: research/sci_comm.qmd
          - text: Journal Club
            href: research/journal_club.qmd

#  cookie-consent:
#    type: express
#    style: headline
#    palette: dark
  google-analytics:
    tracking-id: "G-R9QVZ0JZBJ"
    anonymize-ip: true
  page-footer:
    left: "Website made using [Quarto](https://quarto.org/), by William Okech. License: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    lightbox: true

editor: visual

execute:
  freeze: auto

extensions:
  - jmgirard/embedpdf