---
title: ""
toc: true
---

# Recommended Readings (STEM)

This page contains a list of readings that I would recommend for upper-level undergraduate and graduate students getting started in STEM research. It includes articles focused on best practices, important research papers, and science integrity.

## Best Practices

1)  [How to succeed in science: a concise guide for young biomedical scientists. Part I: taking the plunge.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2685175/) Yewdell JW, Nat Rev Mol Cell Biol. (2008).
2)  [How to succeed in science: a concise guide for young biomedical scientists. Part II: making discoveries.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2675886/) Yewdell JW, Nat Rev Mol Cell Biol. (2008).
3)  [The importance of stupidity in scientific research.](https://pubmed.ncbi.nlm.nih.gov/18492790/) Schwartz MA, J Cell Sci. (2008).
4)  [Unskilled and unaware of it: how difficulties in recognizing one's own incompetence lead to inflated self-assessments (Dunning-Kruger Effect).](https://pubmed.ncbi.nlm.nih.gov/10626367/) Kruger J and Dunning D, J Pers Soc Psychol. (1999).
5)  [How to choose a good scientific problem.](https://pubmed.ncbi.nlm.nih.gov/19782018/) Alon U, Mol Cell. (2009).
6)  [PLOS "Ten Simple Rules" Collection provides a quick, concentrated guide for mastering some of the professional challenges research scientists face in their careers.](https://collections.plos.org/collection/ten-simple-rules/) PloS.
7)  [Resources for PhD Students](https://gdalle.github.io/phd-resources/) Guillaume Dalle.
8)  [Pessimistic scientific articles by Abhishaike Mahajan](https://www.abhishaike.com/p/a-primer-on-my-favorite-pessimistic)
9)  [The Codon Guide to Synthetic Biology](https://www.asimov.press/p/synbio-guide)
10) [How to Read a Scientific Paper](https://www.theopennotebook.com/2018/11/06/how-to-read-a-scientific-paper/)
11) [How To Read Scientific And Research Papers: Advice For Journalists](https://www.journoresources.org.uk/how-to-read-scientific-papers-science-journalism/)

## Challenges

1)  [The Emotional Toll of Graduate School.](https://blogs.scientificamerican.com/observations/the-emotional-toll-of-graduate-school/) Puri P, Sci Am. (2019).
2)  [PhDs: the tortuous truth.](https://www.nature.com/articles/d41586-019-03459-7) Woolston C, Nature (2019).
3)  [Why doing a PhD is often a waste of time](https://medium.economist.com/why-doing-a-phd-is-often-a-waste-of-time-349206f9addb) The Economist, Medium (2016).
4)  [There's an awful cost to getting a PhD that no one talks about](https://qz.com/547641/theres-an-awful-cost-to-getting-a-phd-that-no-one-talks-about) Walker J, Quartz (2015).
5)  [Strategies for Supporting Engineering Student Mental Health](https://journals.flvc.org/cee/article/view/132290) Wilson & Goldberg, CEE (2023).
6)  [Prioritizing mental health and wellness in engineering](https://diversity.asee.org/deicommittee/2022/03/29/prioritizing-mental-health-and-wellness-in-engineering/) S. Wilson, ASEE (2022)
7)  [Falling behind: postdocs in their thirties tire of putting life on hold](https://www.nature.com/articles/d41586-023-03296-9)

## Transformative Research Papers in Biomedical Science (in progress)

1)  [A Programmable Dual-RNA-Guided DNA Endonuclease in Adaptive Bacterial Immunity](https://www.science.org/doi/10.1126/science.1225829) Jinek et al., Science (2012) from the Doudna and Charpentier Lab
2)  [Induction of pluripotent stem cells from mouse embryonic and adult fibroblast cultures by defined factors](https://www.cell.com/cell/fulltext/S0092-8674(06)00976-7) Takahashi et al., Cell (2006) from the Yamanaka Lab
3)  [Induction of pluripotent stem cells from adult human fibroblasts by defined factors](https://www.cell.com/cell/fulltext/S0092-8674(07)01471-7) Takahashi et al., Cell (2006) from the Yamanaka Lab
4)  [Matrix Elasticity Directs Stem Cell Lineage Specification](https://www.sciencedirect.com/science/article/pii/S0092867406009615) Engler et al., Cell (2006) from the Discher Lab

## Statistics

1)  [What exactly is 'N' in cell culture and animal experiments?](https://pubmed.ncbi.nlm.nih.gov/29617358/) Lazic SE et al., PloS Biol. (2018).
2)  [SuperPlots: Communicating reproducibility and variability in cell biology.](https://pubmed.ncbi.nlm.nih.gov/32346721/) Lord SJ et al., J Cell Biol. (2020).
3)  [Ten common statistical mistakes to watch out for when writing or reviewing a manuscript.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6785265/) Makin TR et al. eLife (2019).
4)  [Beyond bar and line graphs: time for a new data presentation paradigm.](https://pubmed.ncbi.nlm.nih.gov/25901488/) Weissgerber TL et al. PloS Biol. (2015).
5)  [Statistical relevance---relevant statistics, part I.](https://pubmed.ncbi.nlm.nih.gov/26392568/) Klaus B EMBO J. (2015).
6)  [Statistical relevance-relevant statistics, part II: presenting experimental data.](https://pubmed.ncbi.nlm.nih.gov/27436873/) Klaus B EMBO J. (2015).
7)  [Ten simple rules for getting started with statistics in graduate school](https://pubmed.ncbi.nlm.nih.gov/35446846/) Zitomer RA et al. PloS Comput Biol. (2022).

## Writing

1)  [ACS Guide to Scholarly Communication.](https://pubs.acs.org/doi/book/10.1021/acsguide) ACS. (2020).
2)  [The art of writing science.](https://onlinelibrary.wiley.com/doi/10.1002/pro.514) Plaxco KW, Prot. Sci. (2010).
3)  [Whitesides' Group: Writing a Paper.](https://onlinelibrary.wiley.com/doi/abs/10.1002/adma.200400767) Whitesides GM, Adv. Mat. (2004).
4)  [How to write a first-class paper.](https://www.nature.com/articles/d41586-018-02404-4) Gewin V, Nature (2018).
5)  [Writing readable prose: When planning a scientific manuscript, following a few simple rules has a large impact.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1559667/) Bredan AS & van Roy F, EMBO Rep. (2006).
6)  [Ten simple rules for structuring papers](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005619) Mensh B & Kording K, PLoS Comp Biol. (2017).
7)  [Write accessibly](https://www.nature.com/articles/s41551-021-00816-8) Editors, Nat Biomed Eng. (2021).
8)  [Ten simple rules for scientists engaging in science communication](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011251)
9)  [Science communication in experimental biology: experiences and recommendations](https://journals.biologists.com/jeb/article/226/16/jeb245780/325883/Science-communication-in-experimental-biology)

## Science Integrity

1)  [Science Integrity Digest](https://scienceintegritydigest.com/) Bik E
2)  [Brookes Lab](https://psblab.org/) Brookes P. [Sample Post focused on "Fake Data"](https://psblab.org/?p=651)
3)  [PubPeer: The Online Journal Club](https://pubpeer.com/)
4)  [For Better Science](https://forbetterscience.com/) Schneider L
5)  [Retraction Watch](https://retractionwatch.com/)
6)  [Automatic detection of image manipulations in the biomedical literature](https://www.nature.com/articles/s41419-018-0430-3) Bucci EM, Cell Death and Disease (2018).
7)  [Learning to identify image manipulations in scientific publications](https://arxiv.org/abs/2102.01874) Mazaheri G et al., arXiv (2021).
8)  [Publishing ethics in the era of paper mills](https://journals.biologists.com/bio/article/9/10/bio056556/222806/Publishing-ethics-in-the-era-of-paper-mills) Hackett R and Kelly S, Biol Open (2020).

## Clear Thinking and Better Decision-Making

1)  [Tools for better thinking](https://untools.co/)
2)  [How to choose the right thinking tool](https://untools.co/thinking-tools-guide/#problem-solving-tools)
3)  [Strategies for Disciplined Choice Making](https://thesystemsthinker.com/habits-of-mind-strategies-for-disciplined-choice-making/)
