---
title: "Journal Club"
format: html
toc: true
---

## Journal Club Presentation Format

### Sample Presentations (Coming Soon)

## Background Papers (In Progress)

### Tissue Engineering and Regenerative Medicine

1)  [Induction of pluripotent stem cells from mouse embryonic and adult fibroblast cultures by defined factors](https://www.cell.com/cell/fulltext/S0092-8674(06)00976-7) Takahashi et al., Cell (2006) 
2)  [Induction of pluripotent stem cells from adult human fibroblasts by defined factors](https://www.cell.com/cell/fulltext/S0092-8674(07)01471-7) Takahashi et al., Cell (2006) 

### Biomaterials

1) [Matrix Elasticity Directs Stem Cell Lineage Specification](https://www.sciencedirect.com/science/article/pii/S0092867406009615) Engler et al., Cell (2006)

### Drug Delivery

### Biomechanics

### Rehabilitation Engineering & Prosthetics

### Neural Engineering & Brain–Computer Interfaces

### Biomedical Signal Processing

### Bioinstrumentation & Medical Devices

### Biomedical Imaging and Optics

### Physiology for Engineers

### Synthetic Biology and Genetic Engineering

1) [A Programmable Dual-RNA-Guided DNA Endonuclease in Adaptive Bacterial Immunity](https://www.science.org/doi/10.1126/science.1225829) Jinek et al., Science (2012) 

### Ethics

### Profesional Skills in Biomedical Engineering

