---
title: "Sample Biomaterials Syllabus"
format: html
---

## Syllabus

Prerequisites: TBD

Lectures: TBD

Tutorials: TBD

Laboratory Sessions: TBD

Instructor: William Okech, PhD

[Email Me](mailto:william.okech@gmail.com)

Course Website: <https://wokech.github.io> –\> **Courses** –\> **Select Course**

### Course Description

Biomaterials play an important role in the life sciences and medicine. They are used to aid in the restoration of function and promote healing after injury and disease. Biomaterials can be of natural, synthetic, or hybrid origin, and they are designed to interact with living systems in a safe and compatible manner. In this course, we will look at various materials including metals, ceramics, plastics, and composites, as well as living cells and tissues that are used to develop biomaterials. Additionally, the course will explore material characterization and testing methods, biocompatibility, and important considerations for the design and manufacture of materials for biomedical applications. In addition to lectures (where relevant), laboratory activities and demonstrations will be performed. Lastly, case studies and contemporary examples will be used to explore new technologies.

### Major Topics Covered

- History and Current Uses of Biomaterials
- Atomic Theory of Materials
- Mechanics of Materials
- Surface vs Bulk Properties of Materials
- Biomaterial-Host Tissue Interactions
- Material Degradation
- Major Biomaterial Groups (Metals, Polymers, Ceramics, and Composites)
- Phase Diagrams and Phase Transformations
- Drug Delivery Systems and Tissue Engineering

### Teaching Organization

- Lectures: TBD
- Tutorials: TBD
- Laboratory Exercises: TBD

### Assessment

- Regular Examination at end of Semester: TBD
- Continuous Assessment: TBD
- The students must complete and pass all the labs before they can be allowed to proceed to the next class.

## Guided Notes (coming soon)

## Reference Textbooks (coming soon)

## Readings (coming soon)

## Optional Resources to Explore

### Journals

- [Biofouling](https://www.tandfonline.com/journals/gbif20)
- [ACS Langmuir](https://pubs.acs.org/journal/langd5)
- [Biomaterials](https://www.sciencedirect.com/journal/biomaterials)
- [Materials Today](https://www.sciencedirect.com/journal/materials-today)
- [Nature Materials](https://www.nature.com/nmat/)
- [Artificial Organs](https://onlinelibrary.wiley.com/journal/15251594)
- [Acta Biomaterialia](https://www.sciencedirect.com/journal/acta-biomaterialia)
- [Bioactive Materials](https://www.sciencedirect.com/journal/bioactive-materials)
- [Biomaterials Science](https://pubs.rsc.org/en/journals/journalissues/bm)
- [ACS Biomacromolecules](https://pubs.acs.org/journal/bomaf6)
- [ACS Applied Biomaterials](https://pubs.acs.org/journal/aabmcb)
- [Tissue Engineering: Part A](https://journals.sagepub.com/home/teaa)
- [Tissue Engineering: Part B](https://journals.sagepub.com/home/teba)
- [Tissue Engineering: Part C](https://journals.sagepub.com/home/tena)
- [ACS Bioconjugate Chemistry](https://pubs.acs.org/journal/bcches)
- [Journal of Controlled Release](https://www.sciencedirect.com/journal/journal-of-controlled-release)
- [Journal of Applied Polymer Science](https://onlinelibrary.wiley.com/journal/10974628)
- [Journal of Functional Biomaterials](https://www.mdpi.com/journal/jfb)
- [Journal of Biomaterials Applications](https://journals.sagepub.com/home/jba)
- [Drug Delivery and Translational Research](https://link.springer.com/journal/13346)
- [ACS Biomaterials Science and Engineering](https://pubs.acs.org/journal/abseba)
- [Journal of Biomedical Materials Research: Part A](https://onlinelibrary.wiley.com/journal/15524965)
- [Journal of Biomedical Materials Research: Part B (Applied Biomaterials)](https://onlinelibrary.wiley.com/journal/15524981)

### Societies

- [Society of Biomaterials](https://biomaterials.org/)
- [Controlled Release Society](https://www.controlledreleasesociety.org/)
- [European Society for Biomaterials](https://esbiomaterials.eu/)
- [Australasian Society for Biomaterials and Tissue Engineering](https://www.asbte.org/)
- [Latin American Society for Biomaterials and Artificial Organs (SLABO)](https://slabo.org.br/)
- [ASAIO (formerly known as the American Society for Artificial Internal Organs)](https://asaio.org/)
